# Generated by Django 4.1.3 on 2022-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_actor_full_name_alter_director_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='storage.actor'),
        ),
        migrations.RemoveField(
            model_name='actor',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.ManyToManyField(to='storage.movie'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='full_name',
            field=models.ManyToManyField(to='storage.movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
