# Generated by Django 4.1.3 on 2022-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_movie_options_movie_actor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='languages',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(to='storage.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(to='storage.writer'),
        ),
        migrations.RemoveField(
            model_name='director',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='director',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
